/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.daemon.Gesture.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.GestureAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Gesture.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.GestureAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class GestureAdaptor
 */

GestureAdaptor::GestureAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

GestureAdaptor::~GestureAdaptor()
{
    // destructor
}

void GestureAdaptor::SetEdgeMoveStopDuration(uint duration)
{
    // handle method call com.deepin.daemon.Gesture.SetEdgeMoveStopDuration
    QMetaObject::invokeMethod(parent(), "SetEdgeMoveStopDuration", Q_ARG(uint, duration));
}

void GestureAdaptor::SetInputIgnore(const QString &node, bool ignore)
{
    // handle method call com.deepin.daemon.Gesture.SetInputIgnore
    QMetaObject::invokeMethod(parent(), "SetInputIgnore", Q_ARG(QString, node), Q_ARG(bool, ignore));
}

void GestureAdaptor::SetShortPressDuration(uint duration)
{
    // handle method call com.deepin.daemon.Gesture.SetShortPressDuration
    QMetaObject::invokeMethod(parent(), "SetShortPressDuration", Q_ARG(uint, duration));
}

