/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.system.SystemInfo.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.SystemInfoAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.SystemInfo.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.SystemInfoAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SystemInfoAdaptor
 */

SystemInfoAdaptor::SystemInfoAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SystemInfoAdaptor::~SystemInfoAdaptor()
{
    // destructor
}

qulonglong SystemInfoAdaptor::currentSpeed() const
{
    // get the value of property CurrentSpeed
    return qvariant_cast< qulonglong >(parent()->property("CurrentSpeed"));
}

qulonglong SystemInfoAdaptor::memorySize() const
{
    // get the value of property MemorySize
    return qvariant_cast< qulonglong >(parent()->property("MemorySize"));
}

QString SystemInfoAdaptor::memorySizeHuman() const
{
    // get the value of property MemorySizeHuman
    return qvariant_cast< QString >(parent()->property("MemorySizeHuman"));
}

