/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.lastore.Updater.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.lastore.UpdaterAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.lastore.Updater.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.lastore.UpdaterAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class UpdaterAdaptor
 */

UpdaterAdaptor::UpdaterAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

UpdaterAdaptor::~UpdaterAdaptor()
{
    // destructor
}

bool UpdaterAdaptor::autoCheckUpdates() const
{
    // get the value of property AutoCheckUpdates
    return qvariant_cast< bool >(parent()->property("AutoCheckUpdates"));
}

bool UpdaterAdaptor::autoDownloadUpdates() const
{
    // get the value of property AutoDownloadUpdates
    return qvariant_cast< bool >(parent()->property("AutoDownloadUpdates"));
}

QString UpdaterAdaptor::mirrorSource() const
{
    // get the value of property MirrorSource
    return qvariant_cast< QString >(parent()->property("MirrorSource"));
}

QStringList UpdaterAdaptor::updatableApps() const
{
    // get the value of property UpdatableApps
    return qvariant_cast< QStringList >(parent()->property("UpdatableApps"));
}

QStringList UpdaterAdaptor::updatablePackages() const
{
    // get the value of property UpdatablePackages
    return qvariant_cast< QStringList >(parent()->property("UpdatablePackages"));
}

void UpdaterAdaptor::RestoreSystemSource()
{
    // handle method call com.deepin.lastore.Updater.RestoreSystemSource
    QMetaObject::invokeMethod(parent(), "RestoreSystemSource");
}

void UpdaterAdaptor::SetAutoCheckUpdates(bool enable)
{
    // handle method call com.deepin.lastore.Updater.SetAutoCheckUpdates
    QMetaObject::invokeMethod(parent(), "SetAutoCheckUpdates", Q_ARG(bool, enable));
}

void UpdaterAdaptor::SetAutoDownloadUpdates(bool enable)
{
    // handle method call com.deepin.lastore.Updater.SetAutoDownloadUpdates
    QMetaObject::invokeMethod(parent(), "SetAutoDownloadUpdates", Q_ARG(bool, enable));
}

void UpdaterAdaptor::SetMirrorSource(const QString &id)
{
    // handle method call com.deepin.lastore.Updater.SetMirrorSource
    QMetaObject::invokeMethod(parent(), "SetMirrorSource", Q_ARG(QString, id));
}

