/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.system.Display.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.DisplayAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.Display.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.DisplayAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DisplayAdaptor
 */

DisplayAdaptor::DisplayAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DisplayAdaptor::~DisplayAdaptor()
{
    // destructor
}

QString DisplayAdaptor::GetConfig()
{
    // handle method call com.deepin.system.Display.GetConfig
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetConfig", Q_RETURN_ARG(QString, out0));
    return out0;
}

void DisplayAdaptor::SetConfig(const QString &in0)
{
    // handle method call com.deepin.system.Display.SetConfig
    QMetaObject::invokeMethod(parent(), "SetConfig", Q_ARG(QString, in0));
}

