/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/session/com.deepin.dde.shutdownFront.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.shutdownFrontAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.shutdownFront.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DDE_SHUTDOWNFRONTADAPTOR_H
#define COM_DEEPIN_DDE_SHUTDOWNFRONTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.shutdownFront.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.shutdownFront
 */
class ShutdownFrontAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.shutdownFront")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.shutdownFront\">\n"
"    <signal name=\"ChangKey\">\n"
"      <arg type=\"s\" name=\"keyEvent\"/>\n"
"    </signal>\n"
"    <method name=\"Hibernate\"/>\n"
"    <method name=\"Lock\"/>\n"
"    <method name=\"Logout\"/>\n"
"    <method name=\"Restart\"/>\n"
"    <method name=\"Show\"/>\n"
"    <method name=\"Shutdown\"/>\n"
"    <method name=\"Suspend\"/>\n"
"    <method name=\"SwitchUser\"/>\n"
"  </interface>\n"
        "")
public:
    ShutdownFrontAdaptor(QObject *parent);
    virtual ~ShutdownFrontAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Hibernate();
    void Lock();
    void Logout();
    void Restart();
    void Show();
    void Shutdown();
    void Suspend();
    void SwitchUser();
Q_SIGNALS: // SIGNALS
    void ChangKey(const QString &keyEvent);
};

#endif
