/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.daemon.PasswdConf.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.PasswdConfAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.PasswdConf.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.PasswdConfAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PasswdConfAdaptor
 */

PasswdConfAdaptor::PasswdConfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PasswdConfAdaptor::~PasswdConfAdaptor()
{
    // destructor
}

void PasswdConfAdaptor::Backup()
{
    // handle method call com.deepin.daemon.PasswdConf.Backup
    QMetaObject::invokeMethod(parent(), "Backup");
}

bool PasswdConfAdaptor::GetEnabled()
{
    // handle method call com.deepin.daemon.PasswdConf.GetEnabled
    bool enabled;
    QMetaObject::invokeMethod(parent(), "GetEnabled", Q_RETURN_ARG(bool, enabled));
    return enabled;
}

bool PasswdConfAdaptor::GetFirstLetterUpper()
{
    // handle method call com.deepin.daemon.PasswdConf.GetFirstLetterUpper
    bool enabled;
    QMetaObject::invokeMethod(parent(), "GetFirstLetterUpper", Q_RETURN_ARG(bool, enabled));
    return enabled;
}

int PasswdConfAdaptor::GetLengthLimit(int &maxLength)
{
    // handle method call com.deepin.daemon.PasswdConf.GetLengthLimit
    //return static_cast<YourObjectType *>(parent())->GetLengthLimit(maxLength);
}

QString PasswdConfAdaptor::GetValidatePolicy()
{
    // handle method call com.deepin.daemon.PasswdConf.GetValidatePolicy
    QString validatePolicy;
    QMetaObject::invokeMethod(parent(), "GetValidatePolicy", Q_RETURN_ARG(QString, validatePolicy));
    return validatePolicy;
}

int PasswdConfAdaptor::GetValidateRequired()
{
    // handle method call com.deepin.daemon.PasswdConf.GetValidateRequired
    int validateRequired;
    QMetaObject::invokeMethod(parent(), "GetValidateRequired", Q_RETURN_ARG(int, validateRequired));
    return validateRequired;
}

QString PasswdConfAdaptor::ReadConfig()
{
    // handle method call com.deepin.daemon.PasswdConf.ReadConfig
    QString data;
    QMetaObject::invokeMethod(parent(), "ReadConfig", Q_RETURN_ARG(QString, data));
    return data;
}

void PasswdConfAdaptor::Reset()
{
    // handle method call com.deepin.daemon.PasswdConf.Reset
    QMetaObject::invokeMethod(parent(), "Reset");
}

void PasswdConfAdaptor::SetEnabled(bool enabled)
{
    // handle method call com.deepin.daemon.PasswdConf.SetEnabled
    QMetaObject::invokeMethod(parent(), "SetEnabled", Q_ARG(bool, enabled));
}

void PasswdConfAdaptor::SetFirstLetterUpper(bool enabled)
{
    // handle method call com.deepin.daemon.PasswdConf.SetFirstLetterUpper
    QMetaObject::invokeMethod(parent(), "SetFirstLetterUpper", Q_ARG(bool, enabled));
}

void PasswdConfAdaptor::SetLengthLimit(int minLength, int maxLength)
{
    // handle method call com.deepin.daemon.PasswdConf.SetLengthLimit
    QMetaObject::invokeMethod(parent(), "SetLengthLimit", Q_ARG(int, minLength), Q_ARG(int, maxLength));
}

void PasswdConfAdaptor::SetValidatePolicy(const QString &validatePolicy)
{
    // handle method call com.deepin.daemon.PasswdConf.SetValidatePolicy
    QMetaObject::invokeMethod(parent(), "SetValidatePolicy", Q_ARG(QString, validatePolicy));
}

void PasswdConfAdaptor::SetValidateRequired(int validateRequired)
{
    // handle method call com.deepin.daemon.PasswdConf.SetValidateRequired
    QMetaObject::invokeMethod(parent(), "SetValidateRequired", Q_ARG(int, validateRequired));
}

void PasswdConfAdaptor::WriteConfig(const QString &data)
{
    // handle method call com.deepin.daemon.PasswdConf.WriteConfig
    QMetaObject::invokeMethod(parent(), "WriteConfig", Q_ARG(QString, data));
}

