/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/session/com.deepin.daemon.Audio.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.AudioAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Audio.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.AudioAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AudioAdaptor
 */

AudioAdaptor::AudioAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AudioAdaptor::~AudioAdaptor()
{
    // destructor
}

bool AudioAdaptor::audioServerState() const
{
    // get the value of property AudioServerState
    return qvariant_cast< bool >(parent()->property("AudioServerState"));
}

QString AudioAdaptor::bluetoothAudioMode() const
{
    // get the value of property BluetoothAudioMode
    return qvariant_cast< QString >(parent()->property("BluetoothAudioMode"));
}

QStringList AudioAdaptor::bluetoothAudioModeOpts() const
{
    // get the value of property BluetoothAudioModeOpts
    return qvariant_cast< QStringList >(parent()->property("BluetoothAudioModeOpts"));
}

QString AudioAdaptor::cards() const
{
    // get the value of property Cards
    return qvariant_cast< QString >(parent()->property("Cards"));
}

QString AudioAdaptor::cardsWithoutUnavailable() const
{
    // get the value of property CardsWithoutUnavailable
    return qvariant_cast< QString >(parent()->property("CardsWithoutUnavailable"));
}

QString AudioAdaptor::currentAudioServer() const
{
    // get the value of property CurrentAudioServer
    return qvariant_cast< QString >(parent()->property("CurrentAudioServer"));
}

QDBusObjectPath AudioAdaptor::defaultSink() const
{
    // get the value of property DefaultSink
    return qvariant_cast< QDBusObjectPath >(parent()->property("DefaultSink"));
}

QDBusObjectPath AudioAdaptor::defaultSource() const
{
    // get the value of property DefaultSource
    return qvariant_cast< QDBusObjectPath >(parent()->property("DefaultSource"));
}

bool AudioAdaptor::increaseVolume() const
{
    // get the value of property IncreaseVolume
    return qvariant_cast< bool >(parent()->property("IncreaseVolume"));
}

void AudioAdaptor::setIncreaseVolume(bool value)
{
    // set the value of property IncreaseVolume
    parent()->setProperty("IncreaseVolume", QVariant::fromValue(value));
}

double AudioAdaptor::maxUIVolume() const
{
    // get the value of property MaxUIVolume
    return qvariant_cast< double >(parent()->property("MaxUIVolume"));
}

bool AudioAdaptor::pausePlayer() const
{
    // get the value of property PausePlayer
    return qvariant_cast< bool >(parent()->property("PausePlayer"));
}

void AudioAdaptor::setPausePlayer(bool value)
{
    // set the value of property PausePlayer
    parent()->setProperty("PausePlayer", QVariant::fromValue(value));
}

bool AudioAdaptor::reduceNoise() const
{
    // get the value of property ReduceNoise
    return qvariant_cast< bool >(parent()->property("ReduceNoise"));
}

void AudioAdaptor::setReduceNoise(bool value)
{
    // set the value of property ReduceNoise
    parent()->setProperty("ReduceNoise", QVariant::fromValue(value));
}

QList<QDBusObjectPath> AudioAdaptor::sinkInputs() const
{
    // get the value of property SinkInputs
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("SinkInputs"));
}

QList<QDBusObjectPath> AudioAdaptor::sinks() const
{
    // get the value of property Sinks
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Sinks"));
}

QList<QDBusObjectPath> AudioAdaptor::sources() const
{
    // get the value of property Sources
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Sources"));
}

bool AudioAdaptor::IsPortEnabled(uint in0, const QString &in1)
{
    // handle method call com.deepin.daemon.Audio.IsPortEnabled
    bool out0;
    QMetaObject::invokeMethod(parent(), "IsPortEnabled", Q_RETURN_ARG(bool, out0), Q_ARG(uint, in0), Q_ARG(QString, in1));
    return out0;
}

void AudioAdaptor::Reset()
{
    // handle method call com.deepin.daemon.Audio.Reset
    QMetaObject::invokeMethod(parent(), "Reset");
}

void AudioAdaptor::SetBluetoothAudioMode(const QString &in0)
{
    // handle method call com.deepin.daemon.Audio.SetBluetoothAudioMode
    QMetaObject::invokeMethod(parent(), "SetBluetoothAudioMode", Q_ARG(QString, in0));
}

void AudioAdaptor::SetDefaultSink(const QString &in0)
{
    // handle method call com.deepin.daemon.Audio.SetDefaultSink
    QMetaObject::invokeMethod(parent(), "SetDefaultSink", Q_ARG(QString, in0));
}

void AudioAdaptor::SetDefaultSource(const QString &in0)
{
    // handle method call com.deepin.daemon.Audio.SetDefaultSource
    QMetaObject::invokeMethod(parent(), "SetDefaultSource", Q_ARG(QString, in0));
}

void AudioAdaptor::SetPort(uint in0, const QString &in1, int in2)
{
    // handle method call com.deepin.daemon.Audio.SetPort
    QMetaObject::invokeMethod(parent(), "SetPort", Q_ARG(uint, in0), Q_ARG(QString, in1), Q_ARG(int, in2));
}

void AudioAdaptor::SetPortEnabled(uint in0, const QString &in1, bool in2)
{
    // handle method call com.deepin.daemon.Audio.SetPortEnabled
    QMetaObject::invokeMethod(parent(), "SetPortEnabled", Q_ARG(uint, in0), Q_ARG(QString, in1), Q_ARG(bool, in2));
}

