/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/session/com.deepin.daemon.InputDevices.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.InputDevicesAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.InputDevices.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DAEMON_INPUTDEVICESADAPTOR_H
#define COM_DEEPIN_DAEMON_INPUTDEVICESADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.InputDevices.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.daemon.InputDevices
 */
class InputDevicesAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.daemon.InputDevices")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.daemon.InputDevices\">\n"
"    <property access=\"read\" type=\"a(ss)\" name=\"Infos\">\n"
"      <annotation value=\"InputDeviceList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"readwrite\" type=\"u\" name=\"WheelSpeed\"/>\n"
"  </interface>\n"
        "")
public:
    InputDevicesAdaptor(QObject *parent);
    virtual ~InputDevicesAdaptor();

public: // PROPERTIES
    Q_PROPERTY(InputDeviceList Infos READ infos)
    InputDeviceList infos() const;

    Q_PROPERTY(uint WheelSpeed READ wheelSpeed WRITE setWheelSpeed)
    uint wheelSpeed() const;
    void setWheelSpeed(uint value);

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
