/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/session/com.deepin.dde.TrayManager.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.TrayManagerAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.TrayManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.TrayManagerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TrayManagerAdaptor
 */

TrayManagerAdaptor::TrayManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TrayManagerAdaptor::~TrayManagerAdaptor()
{
    // destructor
}

QList<uint> TrayManagerAdaptor::trayIcons() const
{
    // get the value of property TrayIcons
    return qvariant_cast< QList<uint> >(parent()->property("TrayIcons"));
}

void TrayManagerAdaptor::EnableNotification(uint win, bool enabled)
{
    // handle method call com.deepin.dde.TrayManager.EnableNotification
    QMetaObject::invokeMethod(parent(), "EnableNotification", Q_ARG(uint, win), Q_ARG(bool, enabled));
}

QString TrayManagerAdaptor::GetName(uint win)
{
    // handle method call com.deepin.dde.TrayManager.GetName
    QString name;
    QMetaObject::invokeMethod(parent(), "GetName", Q_RETURN_ARG(QString, name), Q_ARG(uint, win));
    return name;
}

bool TrayManagerAdaptor::Manage()
{
    // handle method call com.deepin.dde.TrayManager.Manage
    bool ok;
    QMetaObject::invokeMethod(parent(), "Manage", Q_RETURN_ARG(bool, ok));
    return ok;
}

