/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/session/com.deepin.dde.osd.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.osdAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.osd.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DDE_OSDADAPTOR_H
#define COM_DEEPIN_DDE_OSDADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.osd.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.osd
 */
class OsdAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.osd")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.osd\">\n"
"    <method name=\"ShowOSD\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"osd\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    OsdAdaptor(QObject *parent);
    virtual ~OsdAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void ShowOSD(const QString &osd);
Q_SIGNALS: // SIGNALS
};

#endif
