/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.daemon.Gesture.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.GestureAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Gesture.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DAEMON_GESTUREADAPTOR_H
#define COM_DEEPIN_DAEMON_GESTUREADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Gesture.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.daemon.Gesture
 */
class GestureAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.daemon.Gesture")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.daemon.Gesture\">\n"
"    <method name=\"SetShortPressDuration\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"duration\"/>\n"
"    </method>\n"
"    <method name=\"SetEdgeMoveStopDuration\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"duration\"/>\n"
"    </method>\n"
"    <method name=\"SetInputIgnore\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"node\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"ignore\"/>\n"
"    </method>\n"
"    <signal name=\"Event\">\n"
"      <arg type=\"s\" name=\"name\"/>\n"
"      <arg type=\"s\" name=\"direction\"/>\n"
"      <arg type=\"i\" name=\"fingers\"/>\n"
"    </signal>\n"
"    <signal name=\"DbclickDown\">\n"
"      <arg type=\"i\" name=\"fingers\"/>\n"
"    </signal>\n"
"    <signal name=\"SwipeMoving\">\n"
"      <arg type=\"i\" name=\"fingers\"/>\n"
"      <arg type=\"d\" name=\"accelX\"/>\n"
"      <arg type=\"d\" name=\"accely\"/>\n"
"    </signal>\n"
"    <signal name=\"SwipeStop\">\n"
"      <arg type=\"i\" name=\"fingers\"/>\n"
"    </signal>\n"
"    <signal name=\"TouchEdgeEvent\">\n"
"      <arg type=\"s\" name=\"direction\"/>\n"
"      <arg type=\"d\" name=\"scalex\"/>\n"
"      <arg type=\"d\" name=\"scaley\"/>\n"
"    </signal>\n"
"    <signal name=\"TouchSinglePressTimeout\">\n"
"      <arg type=\"i\" name=\"time\"/>\n"
"      <arg type=\"d\" name=\"scalex\"/>\n"
"      <arg type=\"d\" name=\"scaley\"/>\n"
"    </signal>\n"
"    <signal name=\"TouchPressTimeout\">\n"
"      <arg type=\"i\" name=\"fingers\"/>\n"
"      <arg type=\"i\" name=\"time\"/>\n"
"      <arg type=\"d\" name=\"scalex\"/>\n"
"      <arg type=\"d\" name=\"scaley\"/>\n"
"    </signal>\n"
"    <signal name=\"TouchUpOrCancel\">\n"
"      <arg type=\"d\" name=\"scalex\"/>\n"
"      <arg type=\"d\" name=\"scaley\"/>\n"
"    </signal>\n"
"    <signal name=\"TouchEdgeMoveStop\">\n"
"      <arg type=\"s\" name=\"direction\"/>\n"
"      <arg type=\"d\" name=\"scalex\"/>\n"
"      <arg type=\"d\" name=\"scaley\"/>\n"
"      <arg type=\"i\" name=\"duration\"/>\n"
"    </signal>\n"
"    <signal name=\"TouchEdgeMoveStopLeave\">\n"
"      <arg type=\"s\" name=\"direction\"/>\n"
"      <arg type=\"d\" name=\"scalex\"/>\n"
"      <arg type=\"d\" name=\"scaley\"/>\n"
"      <arg type=\"i\" name=\"duration\"/>\n"
"    </signal>\n"
"    <signal name=\"TouchMoving\">\n"
"      <arg type=\"d\" name=\"scalex\"/>\n"
"      <arg type=\"d\" name=\"scaley\"/>\n"
"    </signal>\n"
"    <signal name=\"TouchMovementEvent\">\n"
"      <arg type=\"s\" name=\"duration\"/>\n"
"      <arg type=\"i\" name=\"fingers\"/>\n"
"      <arg type=\"d\" name=\"startScalex\"/>\n"
"      <arg type=\"d\" name=\"startScaley\"/>\n"
"      <arg type=\"d\" name=\"endScalex\"/>\n"
"      <arg type=\"d\" name=\"endScaley\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    GestureAdaptor(QObject *parent);
    virtual ~GestureAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void SetEdgeMoveStopDuration(uint duration);
    void SetInputIgnore(const QString &node, bool ignore);
    void SetShortPressDuration(uint duration);
Q_SIGNALS: // SIGNALS
    void DbclickDown(int fingers);
    void Event(const QString &name, const QString &direction, int fingers);
    void SwipeMoving(int fingers, double accelX, double accely);
    void SwipeStop(int fingers);
    void TouchEdgeEvent(const QString &direction, double scalex, double scaley);
    void TouchEdgeMoveStop(const QString &direction, double scalex, double scaley, int duration);
    void TouchEdgeMoveStopLeave(const QString &direction, double scalex, double scaley, int duration);
    void TouchMovementEvent(const QString &duration, int fingers, double startScalex, double startScaley, double endScalex, double endScaley);
    void TouchMoving(double scalex, double scaley);
    void TouchPressTimeout(int fingers, int time, double scalex, double scaley);
    void TouchSinglePressTimeout(int time, double scalex, double scaley);
    void TouchUpOrCancel(double scalex, double scaley);
};

#endif
