/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/session/com.deepin.dde.TrayManager.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.TrayManagerAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.TrayManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DDE_TRAYMANAGERADAPTOR_H
#define COM_DEEPIN_DDE_TRAYMANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.TrayManager.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.dde.TrayManager
 */
class TrayManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.dde.TrayManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.dde.TrayManager\">\n"
"    <method name=\"EnableNotification\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"win\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"GetName\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"win\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"Manage\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"ok\"/>\n"
"    </method>\n"
"    <signal name=\"Inited\"/>\n"
"    <signal name=\"Added\">\n"
"      <arg type=\"u\" name=\"id\"/>\n"
"    </signal>\n"
"    <signal name=\"Removed\">\n"
"      <arg type=\"u\" name=\"id\"/>\n"
"    </signal>\n"
"    <signal name=\"Changed\">\n"
"      <arg type=\"u\" name=\"id\"/>\n"
"    </signal>\n"
"    <property access=\"read\" type=\"au\" name=\"TrayIcons\">\n"
"      <annotation value=\"QList&lt;uint&gt;\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"  </interface>\n"
        "")
public:
    TrayManagerAdaptor(QObject *parent);
    virtual ~TrayManagerAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QList<uint> TrayIcons READ trayIcons)
    QList<uint> trayIcons() const;

public Q_SLOTS: // METHODS
    void EnableNotification(uint win, bool enabled);
    QString GetName(uint win);
    bool Manage();
Q_SIGNALS: // SIGNALS
    void Added(uint id);
    void Changed(uint id);
    void Inited();
    void Removed(uint id);
};

#endif
