/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.system.SystemInfo.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.SystemInfoAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.SystemInfo.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_SYSTEM_SYSTEMINFOADAPTOR_H
#define COM_DEEPIN_SYSTEM_SYSTEMINFOADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.SystemInfo.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.system.SystemInfo
 */
class SystemInfoAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.system.SystemInfo")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.system.SystemInfo\">\n"
"    <property access=\"read\" type=\"s\" name=\"MemorySizeHuman\"/>\n"
"    <property access=\"read\" type=\"t\" name=\"MemorySize\"/>\n"
"    <property access=\"read\" type=\"t\" name=\"CurrentSpeed\"/>\n"
"  </interface>\n"
        "")
public:
    SystemInfoAdaptor(QObject *parent);
    virtual ~SystemInfoAdaptor();

public: // PROPERTIES
    Q_PROPERTY(qulonglong CurrentSpeed READ currentSpeed)
    qulonglong currentSpeed() const;

    Q_PROPERTY(qulonglong MemorySize READ memorySize)
    qulonglong memorySize() const;

    Q_PROPERTY(QString MemorySizeHuman READ memorySizeHuman)
    QString memorySizeHuman() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
