/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.system.Network.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.NetworkAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.Network.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_SYSTEM_NETWORKADAPTOR_H
#define COM_DEEPIN_SYSTEM_NETWORKADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.system.Network.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.system.Network
 */
class NetworkAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.system.Network")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.system.Network\">\n"
"    <method name=\"EnableDevice\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"pathOrIface\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"cpath\"/>\n"
"    </method>\n"
"    <method name=\"IsDeviceEnabled\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"pathOrIface\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"Ping\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"host\"/>\n"
"    </method>\n"
"    <method name=\"ToggleWirelessEnabled\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <signal name=\"DeviceEnabled\">\n"
"      <arg type=\"o\" name=\"devPath\"/>\n"
"      <arg type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <property access=\"readwrite\" type=\"b\" name=\"VpnEnabled\"/>\n"
"  </interface>\n"
        "")
public:
    NetworkAdaptor(QObject *parent);
    virtual ~NetworkAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool VpnEnabled READ vpnEnabled WRITE setVpnEnabled)
    bool vpnEnabled() const;
    void setVpnEnabled(bool value);

public Q_SLOTS: // METHODS
    QDBusObjectPath EnableDevice(const QString &pathOrIface, bool enabled);
    bool IsDeviceEnabled(const QString &pathOrIface);
    void Ping(const QString &host);
    bool ToggleWirelessEnabled();
Q_SIGNALS: // SIGNALS
    void DeviceEnabled(const QDBusObjectPath &devPath, bool enabled);
};

#endif
