/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.daemon.PowerManager.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.PowerManagerAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.PowerManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DAEMON_POWERMANAGERADAPTOR_H
#define COM_DEEPIN_DAEMON_POWERMANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.daemon.PowerManager.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.daemon.PowerManager
 */
class PowerManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.daemon.PowerManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.daemon.PowerManager\">\n"
"    <method name=\"CanHibernate\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"can\"/>\n"
"    </method>\n"
"    <method name=\"CanReboot\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"can\"/>\n"
"    </method>\n"
"    <method name=\"CanShutdown\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"can\"/>\n"
"    </method>\n"
"    <method name=\"CanSuspend\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"can\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"s\" name=\"VirtualMachineName\"/>\n"
"  </interface>\n"
        "")
public:
    PowerManagerAdaptor(QObject *parent);
    virtual ~PowerManagerAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString VirtualMachineName READ virtualMachineName)
    QString virtualMachineName() const;

public Q_SLOTS: // METHODS
    bool CanHibernate();
    bool CanReboot();
    bool CanShutdown();
    bool CanSuspend();
Q_SIGNALS: // SIGNALS
};

#endif
