/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/session/com.deepin.dde.Dock.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.DockAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.Dock.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.dde.DockAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DockAdaptor
 */

DockAdaptor::DockAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DockAdaptor::~DockAdaptor()
{
    // destructor
}

DockGeometry DockAdaptor::geometry() const
{
    // get the value of property geometry
    return qvariant_cast< DockGeometry >(parent()->property("geometry"));
}

bool DockAdaptor::showInPrimary() const
{
    // get the value of property showInPrimary
    return qvariant_cast< bool >(parent()->property("showInPrimary"));
}

void DockAdaptor::setShowInPrimary(bool value)
{
    // set the value of property showInPrimary
    parent()->setProperty("showInPrimary", QVariant::fromValue(value));
}

QStringList DockAdaptor::GetLoadedPlugins()
{
    // handle method call com.deepin.dde.Dock.GetLoadedPlugins
    QStringList list;
    QMetaObject::invokeMethod(parent(), "GetLoadedPlugins", Q_RETURN_ARG(QStringList, list));
    return list;
}

void DockAdaptor::ReloadPlugins()
{
    // handle method call com.deepin.dde.Dock.ReloadPlugins
    QMetaObject::invokeMethod(parent(), "ReloadPlugins");
}

void DockAdaptor::callShow()
{
    // handle method call com.deepin.dde.Dock.callShow
    QMetaObject::invokeMethod(parent(), "callShow");
}

QString DockAdaptor::getPluginKey(const QString &pluginName)
{
    // handle method call com.deepin.dde.Dock.getPluginKey
    QString key;
    QMetaObject::invokeMethod(parent(), "getPluginKey", Q_RETURN_ARG(QString, key), Q_ARG(QString, pluginName));
    return key;
}

bool DockAdaptor::getPluginVisible(const QString &pluginName)
{
    // handle method call com.deepin.dde.Dock.getPluginVisible
    bool visible;
    QMetaObject::invokeMethod(parent(), "getPluginVisible", Q_RETURN_ARG(bool, visible), Q_ARG(QString, pluginName));
    return visible;
}

void DockAdaptor::resizeDock(int offset, bool dragging)
{
    // handle method call com.deepin.dde.Dock.resizeDock
    QMetaObject::invokeMethod(parent(), "resizeDock", Q_ARG(int, offset), Q_ARG(bool, dragging));
}

void DockAdaptor::setPluginVisible(const QString &pluginName, bool visible)
{
    // handle method call com.deepin.dde.Dock.setPluginVisible
    QMetaObject::invokeMethod(parent(), "setPluginVisible", Q_ARG(QString, pluginName), Q_ARG(bool, visible));
}

