/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v0/system/com.deepin.lastore.Updater.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.lastore.UpdaterAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.lastore.Updater.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_LASTORE_UPDATERADAPTOR_H
#define COM_DEEPIN_LASTORE_UPDATERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/com.deepin.lastore.Updater.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.lastore.Updater
 */
class UpdaterAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.lastore.Updater")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.lastore.Updater\">\n"
"    <method name=\"RestoreSystemSource\"/>\n"
"    <method name=\"SetAutoCheckUpdates\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\"/>\n"
"    </method>\n"
"    <method name=\"SetAutoDownloadUpdates\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\"/>\n"
"    </method>\n"
"    <method name=\"SetMirrorSource\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"b\" name=\"AutoCheckUpdates\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"AutoDownloadUpdates\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"MirrorSource\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"UpdatableApps\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"UpdatablePackages\"/>\n"
"  </interface>\n"
        "")
public:
    UpdaterAdaptor(QObject *parent);
    virtual ~UpdaterAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool AutoCheckUpdates READ autoCheckUpdates)
    bool autoCheckUpdates() const;

    Q_PROPERTY(bool AutoDownloadUpdates READ autoDownloadUpdates)
    bool autoDownloadUpdates() const;

    Q_PROPERTY(QString MirrorSource READ mirrorSource)
    QString mirrorSource() const;

    Q_PROPERTY(QStringList UpdatableApps READ updatableApps)
    QStringList updatableApps() const;

    Q_PROPERTY(QStringList UpdatablePackages READ updatablePackages)
    QStringList updatablePackages() const;

public Q_SLOTS: // METHODS
    void RestoreSystemSource();
    void SetAutoCheckUpdates(bool enable);
    void SetAutoDownloadUpdates(bool enable);
    void SetMirrorSource(const QString &id);
Q_SIGNALS: // SIGNALS
};

#endif
