/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/system/org.deepin.dde.Lastore1.Job.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Lastore1.JobAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Lastore1.Job.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Lastore1.JobAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class JobAdaptor
 */

JobAdaptor::JobAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

JobAdaptor::~JobAdaptor()
{
    // destructor
}

bool JobAdaptor::cancelable() const
{
    // get the value of property Cancelable
    return qvariant_cast< bool >(parent()->property("Cancelable"));
}

qlonglong JobAdaptor::createTime() const
{
    // get the value of property CreateTime
    return qvariant_cast< qlonglong >(parent()->property("CreateTime"));
}

QString JobAdaptor::description() const
{
    // get the value of property Description
    return qvariant_cast< QString >(parent()->property("Description"));
}

qlonglong JobAdaptor::downloadSize() const
{
    // get the value of property DownloadSize
    return qvariant_cast< qlonglong >(parent()->property("DownloadSize"));
}

QString JobAdaptor::id() const
{
    // get the value of property Id
    return qvariant_cast< QString >(parent()->property("Id"));
}

QString JobAdaptor::name() const
{
    // get the value of property Name
    return qvariant_cast< QString >(parent()->property("Name"));
}

QStringList JobAdaptor::packages() const
{
    // get the value of property Packages
    return qvariant_cast< QStringList >(parent()->property("Packages"));
}

double JobAdaptor::progress() const
{
    // get the value of property Progress
    return qvariant_cast< double >(parent()->property("Progress"));
}

qlonglong JobAdaptor::speed() const
{
    // get the value of property Speed
    return qvariant_cast< qlonglong >(parent()->property("Speed"));
}

QString JobAdaptor::status() const
{
    // get the value of property Status
    return qvariant_cast< QString >(parent()->property("Status"));
}

QString JobAdaptor::type() const
{
    // get the value of property Type
    return qvariant_cast< QString >(parent()->property("Type"));
}

