/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/session/org.deepin.dde.LangSelector1.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.LangSelector1Adaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.LangSelector1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_LANGSELECTOR1ADAPTOR_H
#define ORG_DEEPIN_DDE_LANGSELECTOR1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.LangSelector1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.LangSelector1
 */
class LangSelector1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.LangSelector1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.LangSelector1\">\n"
"    <method name=\"AddLocale\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"DeleteLocale\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"GetLanguageSupportPackages\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"    <method name=\"GetLocaleDescription\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"GetLocaleList\">\n"
"      <arg direction=\"out\" type=\"a(ss)\"/>\n"
"      <annotation value=\"LocaleList\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"Reset\"/>\n"
"    <method name=\"SetLocale\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <signal name=\"Changed\">\n"
"      <arg type=\"s\"/>\n"
"    </signal>\n"
"    <property access=\"read\" type=\"s\" name=\"CurrentLocale\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"LocaleState\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"Locales\"/>\n"
"  </interface>\n"
        "")
public:
    LangSelector1Adaptor(QObject *parent);
    virtual ~LangSelector1Adaptor();

public: // PROPERTIES
    Q_PROPERTY(QString CurrentLocale READ currentLocale)
    QString currentLocale() const;

    Q_PROPERTY(int LocaleState READ localeState)
    int localeState() const;

    Q_PROPERTY(QStringList Locales READ locales)
    QStringList locales() const;

public Q_SLOTS: // METHODS
    void AddLocale(const QString &in0);
    void DeleteLocale(const QString &in0);
    QStringList GetLanguageSupportPackages(const QString &in0);
    QString GetLocaleDescription(const QString &in0);
    LocaleList GetLocaleList();
    void Reset();
    void SetLocale(const QString &in0);
Q_SIGNALS: // SIGNALS
    void Changed(const QString &in0);
};

#endif
