/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/session/org.deepin.dde.Mime1.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Mime1Adaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Mime1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Mime1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Mime1Adaptor
 */

Mime1Adaptor::Mime1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Mime1Adaptor::~Mime1Adaptor()
{
    // destructor
}

void Mime1Adaptor::AddUserApp(const QStringList &mimeTypes, const QString &desktopId)
{
    // handle method call org.deepin.dde.Mime1.AddUserApp
    QMetaObject::invokeMethod(parent(), "AddUserApp", Q_ARG(QStringList, mimeTypes), Q_ARG(QString, desktopId));
}

void Mime1Adaptor::DeleteApp(const QStringList &mimeTypes, const QString &desktopId)
{
    // handle method call org.deepin.dde.Mime1.DeleteApp
    QMetaObject::invokeMethod(parent(), "DeleteApp", Q_ARG(QStringList, mimeTypes), Q_ARG(QString, desktopId));
}

void Mime1Adaptor::DeleteUserApp(const QString &desktopId)
{
    // handle method call org.deepin.dde.Mime1.DeleteUserApp
    QMetaObject::invokeMethod(parent(), "DeleteUserApp", Q_ARG(QString, desktopId));
}

QString Mime1Adaptor::GetDefaultApp(const QString &mimeType)
{
    // handle method call org.deepin.dde.Mime1.GetDefaultApp
    QString defaultApp;
    QMetaObject::invokeMethod(parent(), "GetDefaultApp", Q_RETURN_ARG(QString, defaultApp), Q_ARG(QString, mimeType));
    return defaultApp;
}

QString Mime1Adaptor::ListApps(const QString &mimeType)
{
    // handle method call org.deepin.dde.Mime1.ListApps
    QString apps;
    QMetaObject::invokeMethod(parent(), "ListApps", Q_RETURN_ARG(QString, apps), Q_ARG(QString, mimeType));
    return apps;
}

QString Mime1Adaptor::ListUserApps(const QString &mimeType)
{
    // handle method call org.deepin.dde.Mime1.ListUserApps
    QString userApps;
    QMetaObject::invokeMethod(parent(), "ListUserApps", Q_RETURN_ARG(QString, userApps), Q_ARG(QString, mimeType));
    return userApps;
}

void Mime1Adaptor::SetDefaultApp(const QStringList &mimeTypes, const QString &desktopId)
{
    // handle method call org.deepin.dde.Mime1.SetDefaultApp
    QMetaObject::invokeMethod(parent(), "SetDefaultApp", Q_ARG(QStringList, mimeTypes), Q_ARG(QString, desktopId));
}

