/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/system/org.deepin.dde.Gesture1.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Gesture1Adaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Gesture1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Gesture1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Gesture1Adaptor
 */

Gesture1Adaptor::Gesture1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Gesture1Adaptor::~Gesture1Adaptor()
{
    // destructor
}

void Gesture1Adaptor::SetEdgeMoveStopDuration(uint duration)
{
    // handle method call org.deepin.dde.Gesture1.SetEdgeMoveStopDuration
    QMetaObject::invokeMethod(parent(), "SetEdgeMoveStopDuration", Q_ARG(uint, duration));
}

void Gesture1Adaptor::SetInputIgnore(const QString &node, bool ignore)
{
    // handle method call org.deepin.dde.Gesture1.SetInputIgnore
    QMetaObject::invokeMethod(parent(), "SetInputIgnore", Q_ARG(QString, node), Q_ARG(bool, ignore));
}

void Gesture1Adaptor::SetShortPressDuration(uint duration)
{
    // handle method call org.deepin.dde.Gesture1.SetShortPressDuration
    QMetaObject::invokeMethod(parent(), "SetShortPressDuration", Q_ARG(uint, duration));
}

