/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/system/org.deepin.dde.Grub2.EditAuthentication.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Grub2.EditAuthenticationAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Grub2.EditAuthentication.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_GRUB2_EDITAUTHENTICATIONADAPTOR_H
#define ORG_DEEPIN_DDE_GRUB2_EDITAUTHENTICATIONADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Grub2.EditAuthentication.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Grub2.EditAuthentication
 */
class EditAuthenticationAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Grub2.EditAuthentication")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Grub2.EditAuthentication\">\n"
"    <method name=\"Disable\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"    </method>\n"
"    <method name=\"Enable\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"as\" name=\"EnabledUsers\"/>\n"
"  </interface>\n"
        "")
public:
    EditAuthenticationAdaptor(QObject *parent);
    virtual ~EditAuthenticationAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QStringList EnabledUsers READ enabledUsers)
    QStringList enabledUsers() const;

public Q_SLOTS: // METHODS
    void Disable(const QString &username);
    void Enable(const QString &username, const QString &password);
Q_SIGNALS: // SIGNALS
};

#endif
