/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/system/org.deepin.dde.LockService1.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.LockService1Adaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.LockService1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_LOCKSERVICE1ADAPTOR_H
#define ORG_DEEPIN_DDE_LOCKSERVICE1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.LockService1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.LockService1
 */
class LockService1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.LockService1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.LockService1\">\n"
"    <method name=\"AuthenticateUser\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"    </method>\n"
"    <method name=\"CurrentUser\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"username\"/>\n"
"    </method>\n"
"    <method name=\"IsLiveCD\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"SwitchToUser\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"    </method>\n"
"    <method name=\"UnlockCheck\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"password\"/>\n"
"    </method>\n"
"    <signal name=\"Event\">\n"
"      <arg type=\"u\" name=\"eventType\"/>\n"
"      <arg type=\"u\" name=\"pid\"/>\n"
"      <arg type=\"s\" name=\"username\"/>\n"
"      <arg type=\"s\" name=\"message\"/>\n"
"    </signal>\n"
"    <signal name=\"UserChanged\">\n"
"      <arg type=\"s\" name=\"username\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    LockService1Adaptor(QObject *parent);
    virtual ~LockService1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void AuthenticateUser(const QString &username);
    QString CurrentUser();
    bool IsLiveCD(const QString &username);
    void SwitchToUser(const QString &username);
    void UnlockCheck(const QString &username, const QString &password);
Q_SIGNALS: // SIGNALS
    void Event(uint eventType, uint pid, const QString &username, const QString &message);
    void UserChanged(const QString &username);
};

#endif
