/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/system/org.deepin.dde.Grub2.Theme.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Grub2.ThemeAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Grub2.Theme.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_GRUB2_THEMEADAPTOR_H
#define ORG_DEEPIN_DDE_GRUB2_THEMEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Grub2.Theme.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Grub2.Theme
 */
class ThemeAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Grub2.Theme")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Grub2.Theme\">\n"
"    <method name=\"GetBackground\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"SetBackgroundSourceFile\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"SetItemColor\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"SetSelectedItemColor\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <signal name=\"BackgroundChanged\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Updating\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"ItemColor\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"SelectedItemColor\"/>\n"
"  </interface>\n"
        "")
public:
    ThemeAdaptor(QObject *parent);
    virtual ~ThemeAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString ItemColor READ itemColor)
    QString itemColor() const;

    Q_PROPERTY(QString SelectedItemColor READ selectedItemColor)
    QString selectedItemColor() const;

    Q_PROPERTY(bool Updating READ updating)
    bool updating() const;

public Q_SLOTS: // METHODS
    QString GetBackground();
    void SetBackgroundSourceFile(const QString &in0);
    void SetItemColor(const QString &in0);
    void SetSelectedItemColor(const QString &in0);
Q_SIGNALS: // SIGNALS
    void BackgroundChanged();
};

#endif
