/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/system/org.deepin.dde.SystemInfo1.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemInfo1Adaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemInfo1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_SYSTEMINFO1ADAPTOR_H
#define ORG_DEEPIN_DDE_SYSTEMINFO1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.SystemInfo1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.SystemInfo1
 */
class SystemInfo1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.SystemInfo1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.SystemInfo1\">\n"
"    <property access=\"read\" type=\"s\" name=\"MemorySizeHuman\"/>\n"
"    <property access=\"read\" type=\"t\" name=\"MemorySize\"/>\n"
"    <property access=\"read\" type=\"t\" name=\"CurrentSpeed\"/>\n"
"  </interface>\n"
        "")
public:
    SystemInfo1Adaptor(QObject *parent);
    virtual ~SystemInfo1Adaptor();

public: // PROPERTIES
    Q_PROPERTY(qulonglong CurrentSpeed READ currentSpeed)
    qulonglong currentSpeed() const;

    Q_PROPERTY(qulonglong MemorySize READ memorySize)
    qulonglong memorySize() const;

    Q_PROPERTY(QString MemorySizeHuman READ memorySizeHuman)
    QString memorySizeHuman() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
