/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/session/org.deepin.dde.ShutdownFront1.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.ShutdownFront1Adaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.ShutdownFront1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.ShutdownFront1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ShutdownFront1Adaptor
 */

ShutdownFront1Adaptor::ShutdownFront1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ShutdownFront1Adaptor::~ShutdownFront1Adaptor()
{
    // destructor
}

void ShutdownFront1Adaptor::Hibernate()
{
    // handle method call org.deepin.dde.ShutdownFront1.Hibernate
    QMetaObject::invokeMethod(parent(), "Hibernate");
}

void ShutdownFront1Adaptor::Lock()
{
    // handle method call org.deepin.dde.ShutdownFront1.Lock
    QMetaObject::invokeMethod(parent(), "Lock");
}

void ShutdownFront1Adaptor::Logout()
{
    // handle method call org.deepin.dde.ShutdownFront1.Logout
    QMetaObject::invokeMethod(parent(), "Logout");
}

void ShutdownFront1Adaptor::Restart()
{
    // handle method call org.deepin.dde.ShutdownFront1.Restart
    QMetaObject::invokeMethod(parent(), "Restart");
}

void ShutdownFront1Adaptor::Show()
{
    // handle method call org.deepin.dde.ShutdownFront1.Show
    QMetaObject::invokeMethod(parent(), "Show");
}

void ShutdownFront1Adaptor::Shutdown()
{
    // handle method call org.deepin.dde.ShutdownFront1.Shutdown
    QMetaObject::invokeMethod(parent(), "Shutdown");
}

void ShutdownFront1Adaptor::Suspend()
{
    // handle method call org.deepin.dde.ShutdownFront1.Suspend
    QMetaObject::invokeMethod(parent(), "Suspend");
}

void ShutdownFront1Adaptor::SwitchUser()
{
    // handle method call org.deepin.dde.ShutdownFront1.SwitchUser
    QMetaObject::invokeMethod(parent(), "SwitchUser");
}

