/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/session/org.deepin.dde.ControlCenter1.GrandSearch.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenter1.GrandSearchAdaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenter1.GrandSearch.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.ControlCenter1.GrandSearchAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class GrandSearchAdaptor
 */

GrandSearchAdaptor::GrandSearchAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

GrandSearchAdaptor::~GrandSearchAdaptor()
{
    // destructor
}

bool GrandSearchAdaptor::Action(const QString &json)
{
    // handle method call org.deepin.dde.ControlCenter1.GrandSearch.Action
    bool out0;
    QMetaObject::invokeMethod(parent(), "Action", Q_RETURN_ARG(bool, out0), Q_ARG(QString, json));
    return out0;
}

QString GrandSearchAdaptor::Search(const QString &json)
{
    // handle method call org.deepin.dde.ControlCenter1.GrandSearch.Search
    QString out0;
    QMetaObject::invokeMethod(parent(), "Search", Q_RETURN_ARG(QString, out0), Q_ARG(QString, json));
    return out0;
}

bool GrandSearchAdaptor::Stop(const QString &json)
{
    // handle method call org.deepin.dde.ControlCenter1.GrandSearch.Stop
    bool out0;
    QMetaObject::invokeMethod(parent(), "Stop", Q_RETURN_ARG(bool, out0), Q_ARG(QString, json));
    return out0;
}

