/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-api-proxy/file/dbus/v1/system/org.deepin.dde.Timedate1.xml -a ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Timedate1Adaptor -i ./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Timedate1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-api-proxy/toolGenerate/qdbusxml2cpp/org.deepin.dde.Timedate1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Timedate1Adaptor
 */

Timedate1Adaptor::Timedate1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Timedate1Adaptor::~Timedate1Adaptor()
{
    // destructor
}

QString Timedate1Adaptor::nTPServer() const
{
    // get the value of property NTPServer
    return qvariant_cast< QString >(parent()->property("NTPServer"));
}

void Timedate1Adaptor::SetLocalRTC(bool in0, bool in1, const QString &in2)
{
    // handle method call org.deepin.dde.Timedate1.SetLocalRTC
    QMetaObject::invokeMethod(parent(), "SetLocalRTC", Q_ARG(bool, in0), Q_ARG(bool, in1), Q_ARG(QString, in2));
}

void Timedate1Adaptor::SetNTP(bool in0, const QString &in1)
{
    // handle method call org.deepin.dde.Timedate1.SetNTP
    QMetaObject::invokeMethod(parent(), "SetNTP", Q_ARG(bool, in0), Q_ARG(QString, in1));
}

void Timedate1Adaptor::SetNTPServer(const QString &in0, const QString &in1)
{
    // handle method call org.deepin.dde.Timedate1.SetNTPServer
    QMetaObject::invokeMethod(parent(), "SetNTPServer", Q_ARG(QString, in0), Q_ARG(QString, in1));
}

void Timedate1Adaptor::SetTime(qlonglong in0, bool in1, const QString &in2)
{
    // handle method call org.deepin.dde.Timedate1.SetTime
    QMetaObject::invokeMethod(parent(), "SetTime", Q_ARG(qlonglong, in0), Q_ARG(bool, in1), Q_ARG(QString, in2));
}

void Timedate1Adaptor::SetTimezone(const QString &in0, const QString &in1)
{
    // handle method call org.deepin.dde.Timedate1.SetTimezone
    QMetaObject::invokeMethod(parent(), "SetTimezone", Q_ARG(QString, in0), Q_ARG(QString, in1));
}

